### PR TITLE
Redefine F() as no-op

### PR DESCRIPTION
**Pull request by MCUdude**
See #11 and #53 for details

### CODE REVIEW

**Comment by facchinm** [comment]
Manually merged as https://github.com/arduino/ArduinoCore-megaavr/commit/d316aa62ae4f515095319cd9e8b0ac781daf5fb8 , thanks!

**Comment by MCUdude** [comment]
So how about the *digital_pin_to* arrays where *pgm_read_byte*? We can save some memory and clock cycles by removing all this.

**Comment by facchinm** [comment]
If you want to target it I'll be glad to merge the PR :wink:

**Comment by MCUdude** [comment]
Sure! But I'll have to do some proper testing first, so give me a few days.

**Comment by facchinm** [comment]
Agree, thank you!

**Comment by matthijskooijman** [comment]
I wonder if this is really the cleanest way to fix this. I'm actually a bit surprised that the `F` macro is defined by ArduinoCore-API, since it is rather target-specific. I would have expected each target to define it as a no-op or functional depending on what the target needs. Instead, it seems there is now AVR-specific code (guarded by an `#ifdef __AVR__`) in the generic API repo (https://github.com/arduino/ArduinoCore-API/blob/master/api/String.h#L29-L42), which is a bit smelly. In addition to the definition of `F()`, it seems the API repo also defines AVR-specific handling of FlashStringHelper (e.g. how to print it: https://github.com/arduino/ArduinoCore-API/blob/master/api/Print.cpp#L41-L53

I wonder if this should somehow be done differently? Maybe the `Print::print(__FlashStringHelper*)` should be declared by API but defined by the core? Or should the core and API communicate using macros somehow (so the API can define default nop versions for cores that do not need this, and leave things undefined for cores that do need it)? Hm.

**Pull request closed without merging**
