### PR TITLE
Fixes for F macro

### PR DESCRIPTION
**Pull request by giulcioffi**
This PR is still a draft

### CODE REVIEW

**Comment by matthijskooijman** [comment]
I might not understand the approach of this PR entirely, but it seems the idea is to use the `deprecated-avr-cmp/pgmspace.h` version instead of the avr-libc version to get dummy PROGMEM semantics (like on e.g. SAMD). However, I'm afraid this will break sketches that include `<avr/pgmspace.h>` directly (not for .ino files, since those include `<Arduino.h>` implicitly first, but sketches or libraries with `.c` or `.cpp` files that include `<avr/pgmspace.h>` without first including `<Arduino.h>`), since those would get the avr-libc definitions.

This could be fixed by putting just `deprecated-avr-comp/avr/pgmspace.h` in the  include path to override the avr-libc-supplied version (without also overriding e.g. `interrupt.h`), but that does require some changes in -API I believe (or duplicating `deprecated-avr-comp/avr/pgmspace.h` in this core). This would essentially approach 2 from [my earlier comment](https://github.com/arduino/ArduinoCore-megaavr/issues/62#issuecomment-688502407), which would work, but still suffer from a tiny corner case with code that bypasses the `pgm_load_*` functions by using `lpm` directly.

**Comment by giulcioffi** [comment]
Hi @matthijskooijman, yes this is a draft PR for a possible implementation of your option 2. I opened a PR to be able to visualize the memory usage change.
I modified also the core ArduinoCore-API: [here](https://github.com/giulcioffi/ArduinoCore-API/tree/FmacroIssue) is the branch with the modifications. I modified the CI workflow in order to use it during the sketches compilation.

**Comment by matthijskooijman** [comment]
> I opened a PR to be able to visualize the memory usage change.

Ah, good plan (though I think the cost of option 1. is more in terms of runtime than memory usage, but it would be interesting to see how much effect there is on the memory usage between both options indeed).

**Comment by aentinger** [comment]
Closing, for details see https://github.com/arduino/ArduinoCore-megaavr/issues/62#issuecomment-743159584.

**Pull request closed without merging**
