### PR TITLE
Bump Wire buffer size to 128

### PR DESCRIPTION
**Pull request by sandeepmistry**
@facchinm it's strange that there is 2 buffer size constants, and more than 2 buffers.

Any suggestions on optimizing?

### CODE REVIEW

**Comment by MCUdude** [comment]
128 bytes for each buffer? This will occupy a total of 256 bytes.
For large transmit sequences it would be much better if we could just point to an array and send that directly instead of loading it into the tx buffer.

**Comment by facchinm** [comment]
@MCUdude the RX buffer is needed since all the transaction is IRQ driven (and data must be retrieved in non irq context). When sending we need to enqueue bytes so it's needed there too.

@sandeepmistry two (four) buffers are clearly too much but this library is a straight porting of https://github.com/arduino/ArduinoCore-avr/tree/master/libraries/Wire so it probably can be optimized in some way :wink:

**Comment by facchinm** [comment]
Changing both the defines increases the Wire ram usage to 6*128 bytes (almost 1/6th of the whole chip memory). A refactor is much needed (removing the accessory buffers? unifying at least master and slave ones? )
Any proposal is accepted :slightly_smiling_face:

**Comment by sandeepmistry** [comment]
@facchinm I've pushed some (minimal) changes, changing the buffers in twi.h/twi.c to be pointers. The Wire.cpp sets them where appropriate. Also, not the twi.c related variables are static in the twi.c.

I2C master operations are tested with the on-board ATECC608a, which seem fine to me. We need to do some testing on the I2C slave functional.

**Comment by sandeepmistry** [comment]
Compared to master for the [ECCX08RandomNumber](https://github.com/arduino-libraries/ArduinoECCX08/blob/master/examples/ECCX08RandomNumber/ECCX08RandomNumber.ino) example, this change is now using 71 more bytes of RAM (previously was 652 bytes, now 723 bytes).

**Comment by facchinm** [comment]
@sandeepmistry it looks just perfect.
@goodchip it would be awesome if you could test this PR in your setup with the UNO WiFi r2 as slave, so we can safely say that no regression is being introduced :slightly_smiling_face:

**Comment by goodchip** [comment]
@facchinm, I try this today ;)

**Comment by goodchip** [comment]
@facchinm: tested during the night, no problem since 16h with my configuration.

**Comment by goodchip** [comment]
Always good after 22h of test run :)

**Pull request merged**
