### PR TITLE
Use TCB0 to generate accurate timing + fix formatting

### LINKED ISSUE #20: Millis, micros and delay generated by timer3b
Hi!

I'm working on a 3rd part Arduino core where the goal is to add proper support for the entire megaAVR-0 series (ATmega3208/4808, ATmega3209/4809) and hopefully a handful of new tinyAVRs in the future. I'm doing this based on this repo.

However an issue is that the ATmega4809 is the _only_ devices out there with four 16-bit timers (type B). And, timer3b is used to generate micros in this core. This means that this core will only work with ATmega4809 devices without heavy modification of the timer setup routines.

This may cause problems when it comes to code compatibility between different targets.

Why not use timer0b (TCB0) to generate millis, micros and delay? Timer0 have always beed used for this in the past, and all new AVRs (megaAVR-0, tinyAVR-0, tinyAVR-1 series) have TCB0 available. This would make porting these core files to other AVRs much simpler. 

I could of course change to TCB0 in my own repo, but it would be much better if TCB0 was the default timer no matter what hardware or Arduino core is used.

Everyone will benefit from Arduino support for the new AVR lineup 🙂
New users will discover the new and impressing lineup of AVR microcontrollers, and still being able to write programs for them in an API there already familiar with. And Microchip will sell more AVRs!

### PR DESCRIPTION
**Pull request by MCUdude**
PR to fix #20.

I've tested all PWM outputs using a digital oscilloscope to verify that everything is works like expected. Millis, micros and delay are not affected (also tested with scope) even though TCB0 is now used for accurate timing + PWM output on pin 5 (PF4). 

This means that this core / the Uno Wifi pinout now only relies on TCA0, TCB0 and TCB1.

### CODE REVIEW

**Comment by MCUdude** [comment]
@facchinm can you review this please?

**Comment by facchinm** [comment]
The patch looks fine but, as expected, breaks PWM functionality on pin 6 (which is a big deal for UNO compatibility). I'd keep the `setup_timers()` patch from your branch and rework the `millis()` patch to accept a DEFINE override.
Is it fine for you?

**Comment by MCUdude** [comment]
I thought I was pretty sure that PWM still worked on all output pins? I'll test it again when I get back from work. I'll get back to you this afternoon.

However if I'm not able to come up with a solution that solves this a #define override is fine too.

**Comment by MCUdude** [comment]
BTW any thoughts on tabs vs (two) spaces on future PRs? Personally I prefer (two) spaces for indents, but I'll  use tabs instead if that's the preferred indentation here.

**Comment by facchinm** [comment]
Manually applied after adding the define compatibility layer (UNO WiFi rev2 still uses TB3, while any other board can override it).

**Pull request closed without merging**
